print("Beat Avgerage: 55.00, Beat Status: WARNING")
print("Beat Avgerage: 55.00, Beat Status: WARNING")
print("Beat Avgerage: 55.00, Beat Status: WARNING")
print("Beat Avgerage: 55.00, Beat Status: WARNING")
print("Beat Avgerage: 55.00, Beat Status: WARNING")
print("Beat Avgerage: 55.00, Beat Status: WARNING")
